name: Manual Deploy

on:
  workflow_dispatch:  
    inputs:
      containerresitryname:
        description: 'Container Registry Name'
        required: true
        default: 'acrhexalzdevwesteurope'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'ghostpoc'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: '${{ github.event.inputs.containerResitryName }}.azurecr.io/myapp:latest'