name: Manual Build

on:
  workflow_dispatch:
    inputs:
      containerresitryname:
        description: 'Container Registry Name'
        required: true
        default: 'acrhexalzdevwesteurope'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ github.event.inputs.containerResitryName }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t ${{ github.event.inputs.containerResitryName }}.azurecr.io/myapp
        docker push ${{ github.event.inputs.containerResitryName }}.azurecr.io/myapp